language: minimal

jobs:
    include:
        -   name: "mongo 3.0"
            env: MONGO_VERSION=mongo30
        -   name: "mongo 3.2"
            env: MONGO_VERSION=mongo32
        -   name: "mongo 3.4"
            env: MONGO_VERSION=mongo34
        -   name: "mongo 3.6"
            env: MONGO_VERSION=mongo36
        -   name: "mongo 4.0"
            env: MONGO_VERSION=mongo40

services:
    - docker

script:
    - make run mongo=$MONGO_VERSION
