version: "2"

services:
  php:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - './src:/app/src:cached'
      - app/vendor
      - './Makefile:/app/Makefile:ro'
      # for Composer
      - '~/.ssh:/root/.ssh:ro'
      - '~/.ssh:/var/www/.ssh:ro'
      - '~/.composer/auth.json:/root/.composer/auth.json:ro'
      - '~/.composer/auth.json:/var/www/.composer/auth.json:ro'
      - '~/.composer/cache:/var/www/.composer/:cached'
